apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxmap
  name: nginxmap
spec:
  containers:
  - image: nginx
    name: ngnixmap
    resources: {}
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
        items:
        - key: key4
          path: key
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}