apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: inspect
  name: inspect
  namespace: core
spec:
  containers:
  - image: redis:latest
    name: inspect
    ports:
    - containerPort: 6379
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
