apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: ns-nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 400m
        memory: 3Gi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}