apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-secret
  name: nginx-secret
spec:
  containers:
  - image: nginx
    name: nginx-secret
    env:
      - name: MY_VARIABLE
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: key1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}