apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix-deploy
  namespace: ns-deploy
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3 
  template:
    metadata: 
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
        - name: NGNIX_PORT
          value: "8080"
        ports:
        - containerPort: "$(NGNIX_PORT)"
