apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: inspect
  namespace: core
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: inspect
status:
  loadBalancer: {}