apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    purpose: learning
spec:
  containers:
  - name: mycont
    image: 1fccnf/arg-output
    args: ["--lines 56 –F"]
  restartPolicy: OnFailure
