apiVersion: v1
kind: Pod

metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:

  - name: liveness

    args:
      - /bin/bash
      - -c
      - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600

    image: centos:centos7

    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5

      periodSeconds: 5