apiVersion: v1
kind: Pod
metadata:
 creationTimestamp: null
 labels:
  run: liveness-pod
 name: liveness-pod
spec:
 containers:
 - image: k8s.gcr.io/liveness
    name: liveness-pod
  args:
  - /server
  resources: {}
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /started
      port: 8080
    failureThreshold: 30
    periodSeconds: 10
 dnsPolicy: ClusterFirst
 restartPolicy: Never
status: {}